# Generated by Django 4.2.13 on 2024-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0002_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
