# Generated by Django 4.2.13 on 2024-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0003_video_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='video',
            name='descriptions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='rubric',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='summaries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
