# Generated by Django 4.2.13 on 2024-06-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0004_remove_video_pdf_file_video_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='durations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
