# Generated by Django 5.0.6 on 2024-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tes", "0005_video_durations_video_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
