# Generated by Django 4.1 on 2024-09-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tes", "0005_video_durations_video_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_file", models.FileField(upload_to="generated_content/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_content",
                        to="tes.video",
                    ),
                ),
            ],
        ),
    ]
