# Generated by Django 4.2.13 on 2024-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0006_generatedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
